import { Expediente } from '../comp/dashboard-abogado/expediente.model';

export const EXPEDIENTES_SEED: Omit<Expediente, 'id'>[] = [
  { modulo: 'srt' as const, cuil: '20308694497', nroExpediente: '',          llamador: 'VER',      nombre: 'CORREA MARIO GASTON',                art: 'SWISS MEDICAL', accidente: 'Accidente de Trabajo', localidad: '',            poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20251320994', nroExpediente: '622647/25',  llamador: '',         nombre: 'JIMENEZ WALTER DANIEL',               art: 'PROVINCIA',     accidente: 'Accidente de Trabajo', localidad: '',            poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20160423804', nroExpediente: '545157/25',  llamador: 'JULIAN',   nombre: 'No encontrado',                       art: 'No encontrado', accidente: 'No encontrado',        localidad: 'ROSARIO',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '27372019099', nroExpediente: '470828/25',  llamador: 'JULIAN',   nombre: 'No encontrado',                       art: 'No encontrado', accidente: 'No encontrado',        localidad: 'ROSARIO',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20326595420', nroExpediente: '639279/25',  llamador: 'JULIAN',   nombre: 'No encontrado',                       art: 'No encontrado', accidente: 'No encontrado',        localidad: 'ROSARIO',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20141430107', nroExpediente: '304027/25',  llamador: 'JULIAN',   nombre: 'No encontrado',                       art: 'No encontrado', accidente: 'No encontrado',        localidad: 'ROSARIO',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20293700940', nroExpediente: '63943325',   llamador: 'GEORGINA', nombre: 'PANIGUTTI NICOLAS MATIAS',            art: 'ASOCIART',      accidente: 'Accidente de Trabajo', localidad: 'RAFAELA',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20417922947', nroExpediente: '622635/25',  llamador: 'MATIAS',   nombre: 'FARIAS GENARO RAUL',                  art: 'ASOCIART',      accidente: 'Accidente de Trabajo', localidad: 'RAFAELA',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: true,  ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20332047675', nroExpediente: '6226616/25', llamador: 'MATIAS',   nombre: 'ALARCON JUAN MANUEL',                 art: 'PREVENCION',    accidente: 'Accidente de Trabajo', localidad: 'DESVIO ARIJON',poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20315876929', nroExpediente: '622911/25',  llamador: 'MATIAS',   nombre: 'BONATO DANISA',                       art: 'PROVINCIA',     accidente: 'Accidente de Trabajo', localidad: 'ROSARIO',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20368164063', nroExpediente: '624447/25',  llamador: 'MATIAS',   nombre: 'SALAS ANGEL JESUS',                   art: 'PREVENCION',    accidente: 'Accidente de Trabajo', localidad: 'ROSARIO',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20177641147', nroExpediente: '624655/25',  llamador: 'JULIAN',   nombre: 'LOPEZ JORGE RAMON',                   art: 'ASOCIART',      accidente: 'Accidente de Trabajo', localidad: 'ROSARIO',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '23281268449', nroExpediente: '125437/25',  llamador: 'JULIAN',   nombre: 'SARRIA LEANDRO SEBASTIAN',            art: 'PREVENCION',    accidente: 'Accidente de Trabajo', localidad: 'SANTA FE',    poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20184328438', nroExpediente: '538383/24',  llamador: 'JULIAN',   nombre: 'LOZA EDUARDO HUGO DAVID',             art: 'PREVENCION',    accidente: 'Accidente de Trabajo', localidad: 'AVELLANEDA',  poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '23466536679', nroExpediente: '420289/25',  llamador: 'GEORGINA', nombre: 'CHAVEZ ELIAS RAMON',                  art: 'PREVENCION',    accidente: 'Accidente de Trabajo', localidad: 'RAFAELA',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '27280840691', nroExpediente: '431329/25',  llamador: 'GEORGINA', nombre: 'GONGORA MARIA ROSA',                  art: 'PREVENCION',    accidente: 'Accidente de Trabajo', localidad: 'RAFAELA',     poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
  { modulo: 'srt' as const, cuil: '20335531265', nroExpediente: '473313/25',  llamador: 'GEORGINA', nombre: 'ROMERO RAMIREZ JOAQUIN ALEJANDRO',    art: 'PREVENCION',    accidente: 'Accidente de Trabajo', localidad: 'SANTO TOME',  poder: true, etapa: 'Judicial', certificadoMed: true,  informeMed: true,  certFirmas: false, ratificacion: true, pagare: true, boleta: true },
];
